export const ARG_ENTRY_POINT = 'ENTRY_POINT';
export const ARG_REGISTRY_PORT = 'REGISTRY_PORT';
export const ARG_PARENT_PID = 'PARENT_PID';
export const ARG_HANDLES_UNCAUGHT_ERRORS = 'HANDLES_UNCAUGHT_ERRORS';
export const ARG_INJECT_NODE_MODULE_LOOKUP_PATH = 'INJECT_NODE_MODULE_LOOKUP_PATH';
export const ARG_PACKAGE_FOLDER = 'PACKAGE_FOLDER';
